from django.shortcuts import render,HttpResponse
from googletrans import Translator
import csv
import pandas as pd
import datetime
import pickle
import numpy as np

translator = Translator()

name = ''
lan = ''

def trans(t,s):
    try:
        k= translator.translate(t,s).text
    except:
        k = t
    return k

def login(request):
    return render(request,'login.html')

def get_keys():
    l = [
        "abdominal_pain",
        "abnormal_menstruation",
        "acidity",
        "acute_liver_failure",
        "altered_sensorium",
        "anxiety",
        "back_pain",
        "belly_pain",
        "blackheads",
        "bladder_discomfort",
        "blister",
        "blood_in_sputum",
        "bloody_stool",
        "blurred_and_distorted_vision",
        "breathlessness",
        "brittle_nails",
        "bruising",
        "burning_micturition",
        "chest_pain",
        "chills",
        "cold_hands_and_feets",
        "coma",
        "congestion",
        "constipation",
        "continuous_feel_of_urine",
        "continuous_sneezing",
        "cough",
        "cramps",
        "dark_urine",
        "dehydration",
        "depression",
        "diarrhoea",
        "dischromic _patches",
        "distention_of_abdomen",
        "dizziness",
        "drying_and_tingling_lips",
        "enlarged_thyroid",
        "excessive_hunger",
        "extra_marital_contacts",
        "family_history",
        "fast_heart_rate",
        "fatigue",
        "fluid_overload",
        "foul_smell_of urine",
        "headache",
        "high_fever",
        "hip_joint_pain",
        "history_of_alcohol_consumption",
        "increased_appetite",
        "indigestion",
        "inflammatory_nails",
        "internal_itching",
        "irregular_sugar_level",
        "irritability",
        "irritation_in_anus",
        "joint_pain",
        "knee_pain",
        "lack_of_concentration",
        "lethargy",
        "loss_of_appetite",
        "loss_of_balance",
        "loss_of_smell",
        "malaise",
        "mild_fever",
        "mood_swings",
        "movement_stiffness",
        "mucoid_sputum",
        "muscle_pain",
        "muscle_wasting",
        "muscle_weakness",
        "nausea",
        "neck_pain",
        "nodal_skin_eruptions",
        "obesity",
        "pain_behind_the_eyes",
        "pain_during_bowel_movements",
        "pain_in_anal_region",
        "painful_walking",
        "palpitations",
        "passage_of_gases",
        "patches_in_throat",
        "phlegm",
        "polyuria",
        "prominent_veins_on_calf",
        "puffy_face_and_eyes",
        "pus_filled_pimples",
        "receiving_blood_transfusion",
        "receiving_unsterile_injections",
        "red_sore_around_nose",
        "red_spots_over_body",
        "redness_of_eyes",
        "restlessness",
        "runny_nose",
        "rusty_sputum",
        "scurring",
        "shivering",
        "silver_like_dusting",
        "sinus_pressure",
        "skin_peeling",
        "skin_rash",
        "slurred_speech",
        "small_dents_in_nails",
        "spinning_movements",
        "spotting_ urination",
        "stiff_neck",
        "stomach_bleeding",
        "stomach_pain",
        "sunken_eyes",
        "sweating",
        "swelled_lymph_nodes",
        "swelling_joints",
        "swelling_of_stomach",
        "swollen_blood_vessels",
        "swollen_extremeties",
        "swollen_legs",
        "throat_irritation",
        "toxic_look_(typhos)",
        "ulcers_on_tongue",
        "unsteadiness",
        "visual_disturbances",
        "vomiting",
        "watering_from_eyes",
        "weakness_in_limbs",
        "weakness_of_one_body_side",
        "weight_gain",
        "weight_loss",
        "yellow_crust_ooze",
        "yellow_urine",
        "yellowing_of_eyes",
        "yellowish_skin",
        "itching"]
    return l
def get_sym(lan):
    if (lan=='hindi'):
        sym = {
            'abdominal_pain': 'पेट में दर्द',
            'abnormal_menstruation': 'असामान्य मासिक धर्म',
            'acidity': 'पेट की गैस',
            'acute_liver_failure': 'तीव्र यकृत विफलता',
            'altered_sensorium': 'बदला हुआ सेंसरियम',
            'anxiety': 'चिंता',
            'back_pain': 'पीठ दर्द',
            'belly_pain': 'पेट दर्द',
            'blackheads': 'ब्लैकहेड्स',
            'bladder_discomfort': 'मूत्राशय की तकलीफ',
            'blister': 'छाला',
            'blood_in_sputum': 'थूक में रक्त',
            'bloody_stool': 'रक्त - युक्त मल',
            'blurred_and_distorted_vision': 'धुंधली और विकृत दृष्टि',
            'breathlessness': 'सांस फूलना',
            'brittle_nails': 'नाज़ुक नाखून',
            'bruising': 'चोट',
            'burning_micturition': 'जलती हुई गदा',
            'chest_pain': 'छाती में दर्द',
            'chills': 'ठंड लगना',
            'cold_hands_and_feets': 'ठंडे हाथ और जाल',
            'coma': 'प्रगाढ़ बेहोशी',
            'congestion': 'भीड़-भाड़',
            'constipation': 'कब्ज़',
            'continuous_feel_of_urine': 'पेशाब का लगातार महसूस होना',
            'continuous_sneezing': 'लगातार छींक आना',
            'cough': 'खांसी',
            'cramps': 'ऐंठन',
            'dark_urine': 'गहरा पेशाब',
            'dehydration': 'निर्जलीकरण',
            'depression': 'डिप्रेशन',
            'diarrhoea': 'दस्त',
            'dischromic _patches': 'डिस्क्रोमिक पैच',
            'distention_of_abdomen': 'उदर की विकृति',
            'dizziness': 'सिर चकराना',
            'drying_and_tingling_lips': 'होंठ सूखना और झुनझुनाहट',
            'enlarged_thyroid': 'बढ़े हुए थायराइड',
            'excessive_hunger': 'अत्यधिक भूख',
            'extra_marital_contacts': 'अतिरिक्त वैवाहिक संपर्क',
            'family_history': 'परिवार के इतिहास',
            'fast_heart_rate': 'तेज हृदय गति',
            'fatigue': 'थकान',
            'fluid_overload': 'द्रव अधिभार',
            'foul_smell_of urine': 'दुर्गंध की दुर्गंध',
            'headache': 'सरदर्द',
            'high_fever': 'तेज़ बुखार',
            'hip_joint_pain': 'जोड़ों का दर्द',
            'history_of_alcohol_consumption': 'शराब सेवन का इतिहास',
            'increased_appetite': 'भूख में वृद्धि',
            'indigestion': 'खट्टी डकार',
            'inflammatory_nails': 'भड़काऊ नाखून',
            'internal_itching': 'आंतरिक खुजली',
            'irregular_sugar_level': 'अनियमित शर्करा स्तर',
            'irritability': 'चिड़चिड़ापन',
            'irritation_in_anus': 'गुदा में जलन',
            'joint_pain': 'जोड़ों का दर्द',
            'knee_pain': 'घुटने के दर्द',
            'lack_of_concentration': 'ध्यान की कमी',
            'lethargy': 'सुस्ती',
            'loss_of_appetite': 'भूख में कमी',
            'loss_of_balance': 'संतुलन की हानि',
            'loss_of_smell': 'गंध का नुकसान',
            'malaise': 'अस्वस्थता',
            'mild_fever': 'हल्का बुखार',
            'mood_swings': 'मिजाज़',
            'movement_stiffness': 'आंदोलन की कठोरता',
            'mucoid_sputum': 'बलगमयुक्त बलगम',
            'muscle_pain': 'मांसपेशियों में दर्द',
            'muscle_wasting': 'मांसपेशी बर्बाद होना',
            'muscle_weakness': 'मांसपेशी में कमज़ोरी',
            'nausea': 'जी मिचलाना',
            'neck_pain': 'गर्दन दर्द',
            'nodal_skin_eruptions': 'नोडल त्वचा का फटना',
            'obesity': 'मोटापा',
            'pain_behind_the_eyes': 'आँखों के पीछे दर्द',
            'pain_during_bowel_movements': 'मल त्याग के दौरान दर्द',
            'pain_in_anal_region': 'गुदा क्षेत्र में दर्द',
            'painful_walking': 'दर्दनाक चलना',
            'palpitations': 'palpitations',
            'passage_of_gases': 'गैसों का मार्ग',
            'patches_in_throat': 'गले में पैच',
            'phlegm': 'कफ',
            'polyuria': 'बहुमूत्रता',
            'prominent_veins_on_calf': 'बछड़े पर प्रमुख नसें',
            'puffy_face_and_eyes': 'फूला हुआ चेहरा और आँखें',
            'pus_filled_pimples': 'मवाद भरा हुआ मवाद',
            'receiving_blood_transfusion': 'रक्त आधान प्राप्त करना',
            'receiving_unsterile_injections': 'अप्रतिबंधित इंजेक्शन प्राप्त करना',
            'red_sore_around_nose': 'नाक के आसपास लाल रंग की खराश',
            'red_spots_over_body': 'शरीर पर लाल धब्बे',
            'redness_of_eyes': 'आँखों की लाली',
            'restlessness': 'बेचैनी',
            'runny_nose': 'बहती नाक',
            'rusty_sputum': 'जंग लगा हुआ थूक',
            'scurring': 'Scurring',
            'shivering': 'कांप',
            'silver_like_dusting': 'चाँदी जैसी धूल',
            'sinus_pressure': 'साइनस दबाव',
            'skin_peeling': 'त्वचा का छिलना',
            'skin_rash': 'त्वचा के लाल चकत्ते',
            'slurred_speech': 'तिरस्कारपूर्ण भाषण',
            'small_dents_in_nails': 'नाखूनों में छोटा डेंट',
            'spinning_movements': 'घूमने की हरकत',
            'spotting_ urination': 'पेशाब का खुल जाना',
            'stiff_neck': 'गर्दन में अकड़न',
            'stomach_bleeding': 'पेट से खून बहना',
            'stomach_pain': 'पेट दर्द',
            'sunken_eyes': 'धंसी हुई आंखें',
            'sweating': 'पसीना आना',
            'swelled_lymph_nodes': 'सूजन लिम्फ नोड्स',
            'swelling_joints': 'जोड़ों में सूजन',
            'swelling_of_stomach': 'पेट की सूजन',
            'swollen_blood_vessels': 'रक्त वाहिकाओं में सूजन',
            'swollen_extremeties': 'सूजन एक्स्ट्रेटीज',
            'swollen_legs': 'पैरों में सूजन',
            'throat_irritation': 'गले में जलन',
            'toxic_look_(typhos)': 'विषैला रूप (टाइफोस)',
            'ulcers_on_tongue': 'जीभ पर अल्सर',
            'unsteadiness': 'अस्थिरता',
            'visual_disturbances': 'देखनेमे िदकत',
            'vomiting': 'उल्टी',
            'watering_from_eyes': 'आँखों से पानी गिरना',
            'weakness_in_limbs': 'अंगों में कमजोरी',
            'weakness_of_one_body_side': 'एक शरीर पक्ष की कमजोरी',
            'weight_gain': 'भार बढ़ना',
            'weight_loss': 'वजन घटना',
            'yellow_crust_ooze': 'पीले रंग की पपड़ी',
            'yellow_urine': 'पीला मूत्र',
            'yellowing_of_eyes': 'आँखों का पीला पड़ना',
            'yellowish_skin': 'पीली त्वचा',
            'itching': 'खुजली'}
    elif (lan == 'english'):
        sym = {
            'abdominal_pain': 'Abdominal pain',
            'abnormal_menstruation': 'Abnormal menstruation',
            'acidity': 'Acidity',
            'acute_liver_failure': 'Acute liver failure',
            'altered_sensorium': 'Altered sensorium',
            'anxiety': 'Anxiety',
            'back_pain': 'Back pain',
            'belly_pain': 'Belly pain',
            'blackheads': 'Blackheads',
            'bladder_discomfort': 'Bladder discomfort',
            'blister': 'Blister',
            'blood_in_sputum': 'Blood in sputum',
            'bloody_stool': 'Bloody stool',
            'blurred_and_distorted_vision': 'Blurred and distorted vision',
            'breathlessness': 'Breathlessness',
            'brittle_nails': 'Brittle nails',
            'bruising': 'Bruising',
            'burning_micturition': 'Burning micturition',
            'chest_pain': 'Chest pain',
            'chills': 'Chills',
            'cold_hands_and_feets': 'Cold hands and feets',
            'coma': 'Coma',
            'congestion': 'Congestion',
            'constipation': 'Constipation',
            'continuous_feel_of_urine': 'Continuous feel of urine',
            'continuous_sneezing': 'Continuous sneezing',
            'cough': 'Cough',
            'cramps': 'Cramps',
            'dark_urine': 'Dark urine',
            'dehydration': 'Dehydration',
            'depression': 'Depression',
            'diarrhoea': 'Diarrhoea',
            'dischromic _patches': 'Dischromic patches',
            'distention_of_abdomen': 'Distention of abdomen',
            'dizziness': 'Dizziness',
            'drying_and_tingling_lips': 'Drying and tingling lips',
            'enlarged_thyroid': 'Enlarged thyroid',
            'excessive_hunger': 'Excessive hunger',
            'extra_marital_contacts': 'Extra marital contacts',
            'family_history': 'Family history',
            'fast_heart_rate': 'Fast heart rate',
            'fatigue': 'Fatigue',
            'fluid_overload': 'Fluid overload',
            'foul_smell_of urine': 'Foul smell ofurine',
            'headache': 'Headache',
            'high_fever': 'High fever',
            'hip_joint_pain': 'Hip joint pain',
            'history_of_alcohol_consumption': 'History of alcohol consumption',
            'increased_appetite': 'Increased appetite',
            'indigestion': 'Indigestion',
            'inflammatory_nails': 'Inflammatory nails',
            'internal_itching': 'Internal itching',
            'irregular_sugar_level': 'Irregular sugar level',
            'irritability': 'Irritability',
            'irritation_in_anus': 'Irritation in anus',
            'joint_pain': 'Joint pain',
            'knee_pain': 'Knee pain',
            'lack_of_concentration': 'Lack of concentration',
            'lethargy': 'Lethargy',
            'loss_of_appetite': 'Loss of appetite',
            'loss_of_balance': 'Loss of balance',
            'loss_of_smell': 'Loss of smell',
            'malaise': 'Malaise',
            'mild_fever': 'Mild fever',
            'mood_swings': 'Mood swings',
            'movement_stiffness': 'Movement stiffness',
            'mucoid_sputum': 'Mucoid sputum',
            'muscle_pain': 'Muscle pain',
            'muscle_wasting': 'Muscle wasting',
            'muscle_weakness': 'Muscle weakness',
            'nausea': 'Nausea',
            'neck_pain': 'Neck pain',
            'nodal_skin_eruptions': 'Nodal skin eruptions',
            'obesity': 'Obesity',
            'pain_behind_the_eyes': 'Pain behind the eyes',
            'pain_during_bowel_movements': 'Pain during bowel movements',
            'pain_in_anal_region': 'Pain in anal region',
            'painful_walking': 'Painful walking',
            'palpitations': 'Palpitations',
            'passage_of_gases': 'Passage of gases',
            'patches_in_throat': 'Patches in throat',
            'phlegm': 'Phlegm',
            'polyuria': 'Polyuria',
            'prominent_veins_on_calf': 'Prominent veins on calf',
            'puffy_face_and_eyes': 'Puffy face and eyes',
            'pus_filled_pimples': 'Pus filled pimples',
            'receiving_blood_transfusion': 'Receiving blood transfusion',
            'receiving_unsterile_injections': 'Receiving unsterile injections',
            'red_sore_around_nose': 'Red sore around nose',
            'red_spots_over_body': 'Red spots over body',
            'redness_of_eyes': 'Redness of eyes',
            'restlessness': 'Restlessness',
            'runny_nose': 'Runny nose',
            'rusty_sputum': 'Rusty sputum',
            'scurring': 'Scurring',
            'shivering': 'Shivering',
            'silver_like_dusting': 'Silver like dusting',
            'sinus_pressure': 'Sinus pressure',
            'skin_peeling': 'Skin peeling',
            'skin_rash': 'Skin rash',
            'slurred_speech': 'Slurred speech',
            'small_dents_in_nails': 'Small dents in nails',
            'spinning_movements': 'Spinning movements',
            'spotting_ urination': 'Spotting urination',
            'stiff_neck': 'Stiff neck',
            'stomach_bleeding': 'Stomach bleeding',
            'stomach_pain': 'Stomach pain',
            'sunken_eyes': 'Sunken eyes',
            'sweating': 'Sweating',
            'swelled_lymph_nodes': 'Swelled lymph nodes',
            'swelling_joints': 'Swelling joints',
            'swelling_of_stomach': 'Swelling of stomach',
            'swollen_blood_vessels': 'Swollen blood vessels',
            'swollen_extremeties': 'Swollen extremeties',
            'swollen_legs': 'Swollen legs',
            'throat_irritation': 'Throat irritation',
            'toxic_look_(typhos)': 'Toxic look (typhos)',
            'ulcers_on_tongue': 'Ulcers on tongue',
            'unsteadiness': 'Unsteadiness',
            'visual_disturbances': 'Visual disturbances',
            'vomiting': 'Vomiting',
            'watering_from_eyes': 'Watering from eyes',
            'weakness_in_limbs': 'Weakness in limbs',
            'weakness_of_one_body_side': 'Weakness of one body side',
            'weight_gain': 'Weight gain',
            'weight_loss': 'Weight loss',
            'yellow_crust_ooze': 'Yellow crust ooze',
            'yellow_urine': 'Yellow urine',
            'yellowing_of_eyes': 'Yellowing of eyes',
            'yellowish_skin': 'Yellowish skin',
            'itching': 'Itching'
            }
    elif (lan == 'punjabi'):
        print('in punjabi')
        sym ={
            'abdominal_pain': 'ਪੇਟ ਦਰਦ',
            'abnormal_menstruation': 'ਅਸਾਧਾਰਣ ਮਾਹਵਾਰੀ',
            'acidity': 'ਐਸਿਡਿਟੀ',
            'acute_liver_failure': 'ਗੰਭੀਰ ਜਿਗਰ ਫੇਲ੍ਹ ਹੋਣਾ',
            'altered_sensorium': 'ਬਦਲਿਆ ਸੈਂਸਰ',
            'anxiety': 'ਚਿੰਤਾ',
            'back_pain': 'ਪਿਠ ਦਰਦ',
            'belly_pain': 'Lyਿੱਡ ਵਿੱਚ ਦਰਦ',
            'blackheads': 'ਬਲੈਕਹੈੱਡਸ',
            'bladder_discomfort': 'ਬਲੈਡਰ ਵਿਚ ਬੇਅਰਾਮੀ',
            'blister': 'ਛਾਲੇ',
            'blood_in_sputum': 'ਥੁੱਕ ਵਿਚ ਲਹੂ',
            'bloody_stool': 'ਖੂਨੀ ਟੱਟੀ',
            'blurred_and_distorted_vision': 'ਧੁੰਦਲੀ ਅਤੇ ਖਰਾਬ ਨਜ਼ਰ',
            'breathlessness': 'ਸਾਹ',
            'brittle_nails': 'ਭੁਰਭੁਰਾ ਨਹੁੰ',
            'bruising': 'ਝੁਲਸਣਾ',
            'burning_micturition': 'ਸਾੜ',
            'chest_pain': 'ਛਾਤੀ ਵਿੱਚ ਦਰਦ',
            'chills': 'ਠੰਡ',
            'cold_hands_and_feets': 'ਠੰਡੇ ਹੱਥ ਅਤੇ ਪੈਰ',
            'coma': 'ਕੋਮਾ',
            'congestion': 'ਭੀੜ',
            'constipation': 'ਕਬਜ਼',
            'continuous_feel_of_urine': 'ਪਿਸ਼ਾਬ ਦੀ ਲਗਾਤਾਰ ਭਾਵਨਾ',
            'continuous_sneezing': 'ਨਿਰੰਤਰ ਛਿੱਕ',
            'cough': 'ਖੰਘ',
            'cramps': 'ਕੜਵੱਲ',
            'dark_urine': 'ਗੂੜ੍ਹਾ ਪਿਸ਼ਾਬ',
            'dehydration': 'ਡੀਹਾਈਡਰੇਸ਼ਨ',
            'depression': 'ਦਬਾਅ',
            'diarrhoea': 'ਦਸਤ',
            'dischromic _patches': 'ਡਿਸਚ੍ਰੋਮਿਕ ਪੈਚ',
            'distention_of_abdomen': 'ਪੇਟ ਦਾ ਧਿਆਨ',
            'dizziness': 'ਚੱਕਰ ਆਉਣੇ',
            'drying_and_tingling_lips': 'ਸੁੱਕਣਾ ਅਤੇ ਬੁੱਲ੍ਹ ਸੁੱਕਣਾ',
            'enlarged_thyroid': 'ਵੱਡਾ ਥਾਇਰਾਇਡ',
            'excessive_hunger': 'ਬਹੁਤ ਜ਼ਿਆਦਾ ਭੁੱਖ',
            'extra_marital_contacts': 'ਵਾਧੂ ਵਿਆਹੁਤਾ ਸੰਪਰਕ',
            'family_history': 'ਪਰਿਵਾਰਕ ਇਤਿਹਾਸ',
            'fast_heart_rate': 'ਤੇਜ਼ ਦਿਲ ਦੀ ਦਰ',
            'fatigue': 'ਥਕਾਵਟ',
            'fluid_overload': 'ਤਰਲ ਭਾਰ',
            'foul_smell_of urine': 'ਬਦਬੂ ਦੀ ਬਦਬੂ',
            'headache': 'ਸਿਰ ਦਰਦ',
            'high_fever': 'ਤੇਜ਼ ਬੁਖਾਰ',
            'hip_joint_pain': 'ਕਮਰ ਦਰਦ',
            'history_of_alcohol_consumption': 'ਸ਼ਰਾਬ ਪੀਣ ਦਾ ਇਤਿਹਾਸ',
            'increased_appetite': 'ਭੁੱਖ ਵੱਧ',
            'indigestion': 'ਬਦਹਜ਼ਮੀ',
            'inflammatory_nails': 'ਜਲਣਸ਼ੀਲ ਨਹੁੰ',
            'internal_itching': 'ਅੰਦਰੂਨੀ ਖੁਜਲੀ',
            'irregular_sugar_level': 'ਖੰਡ ਦਾ ਅਨਿਯਮਿਤ ਪੱਧਰ',
            'irritability': 'ਚਿੜਚਿੜੇਪਨ',
            'irritation_in_anus': 'ਗੁਦਾ ਵਿਚ ਜਲਣ',
            'joint_pain': 'ਜੁਆਇੰਟ ਦਰਦ',
            'knee_pain': 'ਗੋਡੇ ਦੇ ਦਰਦ',
            'lack_of_concentration': 'ਇਕਾਗਰਤਾ ਦੀ ਘਾਟ',
            'lethargy': 'ਸੁਸਤ',
            'loss_of_appetite': 'ਭੁੱਖ ਦੀ ਕਮੀ',
            'loss_of_balance': 'ਸੰਤੁਲਨ ਦੀ ਘਾਟ',
            'loss_of_smell': 'ਗੰਧ ਦਾ ਨੁਕਸਾਨ',
            'malaise': 'ਮਲਾਈਜ',
            'mild_fever': 'ਹਲਕਾ ਬੁਖਾਰ',
            'mood_swings': 'ਮੰਨ ਬਦਲ ਗਿਅਾ',
            'movement_stiffness': 'ਅੰਦੋਲਨ ਦੀ ਕਠੋਰਤਾ',
            'mucoid_sputum': 'ਬਲਗ਼ਮ',
            'muscle_pain': 'ਮਸਲ ਦਰਦ',
            'muscle_wasting': 'ਮਾਸਪੇਸ਼ੀ ਬਰਬਾਦ',
            'muscle_weakness': 'ਮਸਲ ਕਮਜ਼ੋਰੀ',
            'nausea': 'ਮਤਲੀ',
            'neck_pain': 'ਗਰਦਨ ਦਾ ਦਰਦ',
            'nodal_skin_eruptions': 'ਨੋਡਲ ਚਮੜੀ ਫਟਣ',
            'obesity': 'ਮੋਟਾਪਾ',
            'pain_behind_the_eyes': 'ਅੱਖ ਦੇ ਪਿੱਛੇ ਦਰਦ',
            'pain_during_bowel_movements': 'ਟੱਟੀ ਟੱਟੀ ਦੇ ਦੌਰਾਨ ਦਰਦ',
            'pain_in_anal_region': 'ਗੁਦਾ ਦੇ ਖੇਤਰ ਵਿੱਚ ਦਰਦ',
            'painful_walking': 'ਦੁਖਦਾਈ ਤੁਰਨਾ',
            'palpitations': 'ਧੜਕਣ',
            'passage_of_gases': 'ਗੈਸਾਂ ਦਾ ਲੰਘਣਾ',
            'patches_in_throat': 'ਗਲ਼ੇ ਵਿਚ ਪੈਚ',
            'phlegm': 'ਬਲੈਗ',
            'polyuria': 'ਪੋਲੀਰੀਆ',
            'prominent_veins_on_calf': 'ਵੱਛੇ ਉੱਤੇ ਪ੍ਰਮੁੱਖ ਨਾੜੀਆਂ',
            'puffy_face_and_eyes': 'ਅਵੇਸਲਾ ਚਿਹਰਾ ਅਤੇ ਅੱਖਾਂ',
            'pus_filled_pimples': 'ਪੀਸ ਭਰੇ ਮੁਹਾਸੇ',
            'receiving_blood_transfusion': 'ਖੂਨ ਚੜ੍ਹਾਉਣਾ',
            'receiving_unsterile_injections': 'ਬੇਰੋਕ ਟੀਕੇ ਪ੍ਰਾਪਤ ਕਰਨਾ',
            'red_sore_around_nose': 'ਨੱਕ ਦੇ ਦੁਆਲੇ ਲਾਲ ਜ਼ਖ਼ਮ',
            'red_spots_over_body': 'ਸਰੀਰ ਉੱਤੇ ਲਾਲ ਚਟਾਕ',
            'redness_of_eyes': 'ਅੱਖ ਦੀ ਲਾਲੀ',
            'restlessness': 'ਬੇਚੈਨੀ',
            'runny_nose': 'ਵਗਦਾ ਨੱਕ',
            'rusty_sputum': 'ਜੰਗਾਲ ਥੁੱਕ',
            'scurring': 'ਡਰਾਉਣਾ',
            'shivering': 'ਕੰਬ ਰਿਹਾ ਹੈ',
            'silver_like_dusting': 'ਚਾਂਦੀ ਵਾਂਗ ਮਿੱਟੀ',
            'sinus_pressure': 'ਸਾਈਨਸ ਦਾ ਦਬਾਅ',
            'skin_peeling': 'ਚਮੜੀ ਦਾ ਛਿਲਕਾ',
            'skin_rash': 'ਚਮੜੀ ਧੱਫੜ',
            'slurred_speech': 'ਗੰਦੀ ਬੋਲੀ',
            'small_dents_in_nails': 'ਨਹੁੰ ਵਿਚ ਛੋਟੇ ਦੰਦ',
            'spinning_movements': 'ਕਤਾਈ ਅੰਦੋਲਨ',
            'spotting_ urination': 'ਚਟਾਕ ਪਿਸ਼ਾਬ',
            'stiff_neck': 'ਗਰਦਨ ਵਿੱਚ ਅਕੜਾਅ',
            'stomach_bleeding': 'ਪੇਟ ਖੂਨ',
            'stomach_pain': 'ਪੇਟ ਦਰਦ',
            'sunken_eyes': 'ਡੁੱਬੀਆਂ ਅੱਖਾਂ',
            'sweating': 'ਪਸੀਨਾ',
            'swelled_lymph_nodes': 'ਸੁੱਜਿਆ ਲਿੰਫ ਨੋਡ',
            'swelling_joints': 'ਸੋਜ ਜੋਡ਼',
            'swelling_of_stomach': 'ਪੇਟ ਦੀ ਸੋਜ',
            'swollen_blood_vessels': 'ਸੁੱਜੀਆਂ ਖੂਨ ਦੀਆਂ ਨਾੜੀਆਂ',
            'swollen_extremeties': 'ਸੁੱਜੀਆਂ ਅੱਤ',
            'swollen_legs': 'ਸੁੱਜੀਆਂ ਲੱਤਾਂ',
            'throat_irritation': 'ਗਲੇ ਵਿਚ ਜਲਣ',
            'toxic_look_(typhos)': 'ਜ਼ਹਿਰੀਲੀ ਦਿੱਖ (ਟਾਈਫਸ)',
            'ulcers_on_tongue': "ਜੀਭ 'ਤੇ ਫੋੜੇ",
            'unsteadiness': 'ਅਸਥਿਰਤਾ',
            'visual_disturbances': 'ਵਿਜ਼ੂਅਲ ਗੜਬੜੀ',
            'vomiting': 'ਉਲਟੀਆਂ',
            'watering_from_eyes': 'ਅੱਖ ਤੱਕ ਪਾਣੀ ਪਿਲਾਉਣ',
            'weakness_in_limbs': 'ਅੰਗ ਵਿਚ ਕਮਜ਼ੋਰੀ',
            'weakness_of_one_body_side': 'ਸਰੀਰ ਦੇ ਇੱਕ ਪਾਸੇ ਦੀ ਕਮਜ਼ੋਰੀ',
            'weight_gain': 'ਭਾਰ ਵਧਣਾ',
            'weight_loss': 'ਵਜ਼ਨ ਘਟਾਉਣਾ',
            'yellow_crust_ooze': 'ਪੀਲੀ ਛਾਲੇ',
            'yellow_urine': 'ਪੀਲਾ ਪਿਸ਼ਾਬ',
            'yellowing_of_eyes': 'ਅੱਖਾਂ ਦਾ ਪੀਲਾ ਹੋਣਾ',
            'yellowish_skin': 'ਪੀਲੀ ਚਮੜੀ',
            'itching': 'ਖੁਜਲੀ'}
    elif (lan == 'urdu'):
        sym = {
            'abdominal_pain': 'پیٹ کا درد',
            'abnormal_menstruation': 'غیر معمولی حیض',
            'acidity': 'تیزابیت',
            'acute_liver_failure': 'شدید جگر کی ناکامی',
            'altered_sensorium': 'تبدیل شدہ سینسرئیم',
            'anxiety': 'بےچینی',
            'back_pain': 'کمر درد',
            'belly_pain': 'پیٹ میں درد',
            'blackheads': 'بلیک ہیڈز',
            'bladder_discomfort': 'مثانے کی تکلیف',
            'blister': 'آبلہ',
            'blood_in_sputum': 'تھوک میں خون',
            'bloody_stool': 'خونی پاخانہ',
            'blurred_and_distorted_vision': 'دھندلا ہوا اور مسخ شدہ وژن',
            'breathlessness': 'سانس لینا',
            'brittle_nails': 'ٹوٹے ناخن',
            'bruising': 'چوٹ',
            'burning_micturition': 'آتشزدگی جلانا',
            'chest_pain': 'سینے کا درد',
            'chills': 'سردی لگ رہی ہے',
            'cold_hands_and_feets': 'سرد ہاتھ اور پیر',
            'coma': 'کوما',
            'congestion': 'بھیڑ',
            'constipation': 'قبض',
            'continuous_feel_of_urine': 'پیشاب کا مستقل احساس ہونا',
            'continuous_sneezing': 'مسلسل چھینک آنا',
            'cough': 'کھانسی',
            'cramps': 'درد',
            'dark_urine': 'گہرا پیشاب',
            'dehydration': 'پانی کی کمی',
            'depression': 'ذہنی دباؤ',
            'diarrhoea': 'اسہال',
            'dischromic _patches': 'ڈسچرمک پیچ',
            'distention_of_abdomen': 'پیٹ کی رکاوٹ',
            'dizziness': 'چکر آنا',
            'drying_and_tingling_lips': 'خشک اور ہونٹوں کو خشک کرنا',
            'enlarged_thyroid': 'بڑھا ہوا تائرواڈ',
            'excessive_hunger': 'ضرورت سے زیادہ بھوک لگی ہے',
            'extra_marital_contacts': 'اضافی ازدواجی رابطے',
            'family_history': 'خاندانی تاریخ',
            'fast_heart_rate': 'دل کی تیز رفتار',
            'fatigue': 'تھکاوٹ',
            'fluid_overload': 'سیال اوورلوڈ',
            'foul_smell_of urine': 'بدبو آرہی ہے',
            'headache': 'سر درد',
            'high_fever': 'تیز بخار',
            'hip_joint_pain': 'کولہے کے درد',
            'history_of_alcohol_consumption': 'الکحل کے استعمال کی تاریخ',
            'increased_appetite': 'بھوک میں اضافہ',
            'indigestion': 'بدہضمی',
            'inflammatory_nails': 'سوزش ناخن',
            'internal_itching': 'اندرونی خارش',
            'irregular_sugar_level': 'چینی کی فاسد سطح',
            'irritability': 'چڑچڑاپن',
            'irritation_in_anus': 'مقعد میں جلن',
            'joint_pain': 'جوڑوں کا درد',
            'knee_pain': 'گھٹنے کا درد',
            'lack_of_concentration': 'حراستی کی کمی',
            'lethargy': 'سستی',
            'loss_of_appetite': 'بھوک میں کمی',
            'loss_of_balance': 'توازن کھو جانا',
            'loss_of_smell': 'بو کی کمی',
            'malaise': 'مالائیس',
            'mild_fever': 'ہلکا بخار',
            'mood_swings': 'موڈ جھومتے ہیں',
            'movement_stiffness': 'تحریک سختی',
            'mucoid_sputum': 'میوکائڈ تھوک',
            'muscle_pain': 'پٹھوں میں درد',
            'muscle_wasting': 'پٹھوں کا ضیاع',
            'muscle_weakness': 'پٹھوں کی کمزوری',
            'nausea': 'متلی',
            'neck_pain': 'گردن میں درد',
            'nodal_skin_eruptions': 'نوڈل جلد پھٹ پڑتی ہے',
            'obesity': 'موٹاپا',
            'pain_behind_the_eyes': 'آنکھوں کے پیچھے درد',
            'pain_during_bowel_movements': 'آنتوں کی حرکت کے دوران درد',
            'pain_in_anal_region': 'مقعد کے خطے میں درد',
            'painful_walking': 'تکلیف دہ چلنا',
            'palpitations': 'جھوٹ بولنا',
            'passage_of_gases': 'گیسوں کا گزرنا',
            'patches_in_throat': 'حلق میں پیچ',
            'phlegm': 'بلغم',
            'polyuria': 'پولیوریا',
            'prominent_veins_on_calf': 'بچھڑے پر نمایاں رگیں',
            'puffy_face_and_eyes': 'بولڈ چہرہ اور آنکھیں',
            'pus_filled_pimples': 'پیپ بھرا ہوا دلال',
            'receiving_blood_transfusion': 'خون منتقل کرنا',
            'receiving_unsterile_injections': 'بے لگام انجیکشن وصول کرنا',
            'red_sore_around_nose': 'ناک کے گرد سرخ زخم',
            'red_spots_over_body': 'جسم پر سرخ دھبے',
            'redness_of_eyes': 'آنکھوں کی لالی',
            'restlessness': 'بےچینی',
            'runny_nose': 'ناک بہنا',
            'rusty_sputum': 'زنگ آلود تھوک',
            'scurring': 'گھماؤ',
            'shivering': 'کانپ رہا ہے',
            'silver_like_dusting': 'چاندی کی طرح دھول جھونک رہی ہے',
            'sinus_pressure': 'ہڈیوں کا دباؤ',
            'skin_peeling': 'جلد کا چھلکا',
            'skin_rash': 'جلد کی رگڑ',
            'slurred_speech': 'مبہم خطاب',
            'small_dents_in_nails': 'ناخنوں میں چھوٹے ڈینٹ',
            'spinning_movements': 'گھومنے والی حرکتیں',
            'spotting_ urination': 'پیشاب کرنا',
            'stiff_neck': 'گردن میں اکڑاؤ',
            'stomach_bleeding': 'پیٹ میں خون بہہ رہا ہے',
            'stomach_pain': 'پیٹ میں درد',
            'sunken_eyes': 'دبی ہوئی آنکھیں',
            'sweating': 'پسینہ آ رہا ہے',
            'swelled_lymph_nodes': 'سوجن لمف نوڈس',
            'swelling_joints': 'سوجن جوڑ',
            'swelling_of_stomach': 'معدہ کی سوجن',
            'swollen_blood_vessels': 'خون کی رگوں میں سوجن',
            'swollen_extremeties': 'سوجن کی انتہا',
            'swollen_legs': 'ٹانگوں میں سوجن',
            'throat_irritation': 'گلے میں جلن',
            'toxic_look_(typhos)': 'زہریلا نظر (ٹائفاس)',
            'ulcers_on_tongue': 'زبان پر السر',
            'unsteadiness': 'عدم استحکام',
            'visual_disturbances': 'بصری پریشانی',
            'vomiting': 'الٹی',
            'watering_from_eyes': 'آنکھوں سے پانی آرہا ہے',
            'weakness_in_limbs': 'اعضاء میں کمزوری',
            'weakness_of_one_body_side': 'جسم کے ایک پہلو کی کمزوری',
            'weight_gain': 'وزن کا بڑھاؤ',
            'weight_loss': 'وزن میں کمی',
            'yellow_crust_ooze': 'پیلے رنگ کے پرت',
            'yellow_urine': 'پیلا پیشاب',
            'yellowing_of_eyes': 'آنکھوں کا پیلا ہونا',
            'yellowish_skin': 'زرد جلد',
            'itching': 'خارش زدہ'}
    elif (lan == 'malyalam'):
        sym = {
            'abdominal_pain': 'വയറുവേദന',
            'abnormal_menstruation': 'അസാധാരണമായ ആർത്തവം',
            'acidity': 'അസിഡിറ്റി',
            'acute_liver_failure': 'അക്യൂട്ട് കരൾ പരാജയം',
            'altered_sensorium': 'മാറ്റം വരുത്തിയ സെൻസോറിയം',
            'anxiety': 'ഉത്കണ്ഠ',
            'back_pain': 'പുറം വേദന',
            'belly_pain': 'വയറുവേദന',
            'blackheads': 'ബ്ലാക്ക്ഹെഡ്സ്',
            'bladder_discomfort': 'മൂത്രസഞ്ചി അസ്വസ്ഥത',
            'blister': 'ബ്ലിസ്റ്റർ',
            'blood_in_sputum': 'സ്പുതത്തിൽ രക്തം',
            'bloody_stool': 'രക്തരൂക്ഷിതമായ മലം',
            'blurred_and_distorted_vision': 'കാഴ്ച മങ്ങിയതും വികലവുമാണ്',
            'breathlessness': 'ശ്വസനമില്ലായ്മ',
            'brittle_nails': 'പൊട്ടുന്ന നഖങ്ങൾ',
            'bruising': 'ചതവ്',
            'burning_micturition': 'കത്തുന്ന ചിത്രം',
            'chest_pain': 'നെഞ്ച് വേദന',
            'chills': 'ചില്ലുകൾ',
            'cold_hands_and_feets': 'തണുത്ത കൈകളും കാലുകളും',
            'coma': 'കോമ',
            'congestion': 'തിരക്ക്',
            'constipation': 'മലബന്ധം',
            'continuous_feel_of_urine': 'മൂത്രത്തിന്റെ തുടർച്ചയായ അനുഭവം',
            'continuous_sneezing': 'തുടർച്ചയായ തുമ്മൽ',
            'cough': 'ചുമ',
            'cramps': 'മലബന്ധം',
            'dark_urine': 'ഇരുണ്ട മൂത്രം',
            'dehydration': 'നിർജ്ജലീകരണം',
            'depression': 'വിഷാദം',
            'diarrhoea': 'അതിസാരം',
            'dischromic _patches': 'ഡിസ്ക്രോമിക് പാച്ചുകൾ',
            'distention_of_abdomen': 'അടിവയറ്റിലെ അകലം',
            'dizziness': 'തലകറക്കം',
            'drying_and_tingling_lips': 'ചുണ്ടുകൾ വരണ്ടതും ഇഴയുന്നതും',
            'enlarged_thyroid': 'വിശാലമായ തൈറോയ്ഡ്',
            'excessive_hunger': 'അമിതമായ വിശപ്പ്',
            'extra_marital_contacts': 'അധിക വൈവാഹിക കോൺടാക്റ്റുകൾ',
            'family_history': 'കുടുംബ ചരിത്രം',
            'fast_heart_rate': 'വേഗത്തിലുള്ള ഹൃദയമിടിപ്പ്',
            'fatigue': 'ക്ഷീണം',
            'fluid_overload': 'ദ്രാവക ഓവർലോഡ്',
            'foul_smell_of urine': 'ദുർഗന്ധം',
            'headache': 'തലവേദന',
            'high_fever': 'കടുത്ത പനി',
            'hip_joint_pain': 'ഹിപ് സന്ധി വേദന',
            'history_of_alcohol_consumption': 'മദ്യപാനത്തിന്റെ ചരിത്രം',
            'increased_appetite': 'വിശപ്പ് വർദ്ധിച്ചു',
            'indigestion': 'ദഹനക്കേട്',
            'inflammatory_nails': 'കോശജ്വലന നഖങ്ങൾ',
            'internal_itching': 'ആന്തരിക ചൊറിച്ചിൽ',
            'irregular_sugar_level': 'ക്രമരഹിതമായ പഞ്ചസാര നില',
            'irritability': 'ക്ഷോഭം',
            'irritation_in_anus': 'മലദ്വാരത്തിൽ പ്രകോപനം',
            'joint_pain': 'സന്ധി വേദന',
            'knee_pain': 'കാൽമുട്ട് വേദന',
            'lack_of_concentration': 'ഏകാഗ്രതയുടെ അഭാവം',
            'lethargy': 'അലസത',
            'loss_of_appetite': 'വിശപ്പ് കുറവ്',
            'loss_of_balance': 'ബാലൻസ് നഷ്ടപ്പെടുന്നു',
            'loss_of_smell': 'മണം നഷ്ടപ്പെടുന്നു',
            'malaise': 'അസ്വാസ്ഥ്യം',
            'mild_fever': 'നേരിയ പനി',
            'mood_swings': 'മൂഡ് മാറുന്നു',
            'movement_stiffness': 'ചലന കാഠിന്യം',
            'mucoid_sputum': 'മ്യൂക്കോയിഡ് സ്പുതം',
            'muscle_pain': 'പേശി വേദന',
            'muscle_wasting': 'മസിൽ പാഴാക്കൽ',
            'muscle_weakness': 'പേശികളുടെ ബലഹീനത',
            'nausea': 'ഓക്കാനം',
            'neck_pain': 'കഴുത്തു വേദന',
            'nodal_skin_eruptions': 'നോഡൽ തൊലി പൊട്ടിത്തെറിക്കുന്നു',
            'obesity': 'അമിതവണ്ണം',
            'pain_behind_the_eyes': 'കണ്ണുകൾക്ക് പിന്നിൽ വേദന',
            'pain_during_bowel_movements': 'മലവിസർജ്ജന സമയത്ത് വേദന',
            'pain_in_anal_region': 'മലദ്വാരം വേദന',
            'painful_walking': 'വേദനാജനകമായ നടത്തം',
            'palpitations': 'ഹൃദയമിടിപ്പ്',
            'passage_of_gases': 'വാതകങ്ങളുടെ കടന്നുപോകൽ',
            'patches_in_throat': 'തൊണ്ടയിലെ പാടുകൾ',
            'phlegm': 'കഫം',
            'polyuria': 'പോളൂറിയ',
            'prominent_veins_on_calf': 'കാളക്കുട്ടിയെക്കുറിച്ചുള്ള പ്രധാന സിരകൾ',
            'puffy_face_and_eyes': 'മുഖവും കണ്ണുകളും',
            'pus_filled_pimples': 'പീസ് നിറച്ച മുഖക്കുരു',
            'receiving_blood_transfusion': 'രക്തപ്പകർച്ച സ്വീകരിക്കുന്നു',
            'receiving_unsterile_injections': 'അസ്ഥിരമായ കുത്തിവയ്പ്പുകൾ സ്വീകരിക്കുന്നു',
            'red_sore_around_nose': 'മൂക്കിന് ചുറ്റും ചുവന്ന വ്രണം',
            'red_spots_over_body': 'ശരീരത്തിന് മുകളിൽ ചുവന്ന പാടുകൾ',
            'redness_of_eyes': 'കണ്ണുകളുടെ ചുവപ്പ്',
            'restlessness': 'അസ്വസ്ഥത',
            'runny_nose': 'മൂക്കൊലിപ്പ്',
            'rusty_sputum': 'തുരുമ്പിച്ച സ്പുതം',
            'scurring': 'ചുരണ്ടൽ',
            'shivering': 'വിറയ്ക്കുന്നു',
            'silver_like_dusting': 'പൊടിപോലെ വെള്ളി',
            'sinus_pressure': 'സൈനസ് മർദ്ദം',
            'skin_peeling': 'തൊലി തൊലി',
            'skin_rash': 'ചർമ്മ ചുണങ്ങു',
            'slurred_speech': 'മന്ദബുദ്ധിയുള്ള സംസാരം',
            'small_dents_in_nails': 'നഖങ്ങളിൽ ചെറിയ ദന്തങ്ങൾ',
            'spinning_movements': 'സ്പിന്നിംഗ് ചലനങ്ങൾ',
            'spotting_ urination': 'മൂത്രമൊഴിക്കൽ',
            'stiff_neck': 'കഠിനമായ കഴുത്ത്',
            'stomach_bleeding': 'വയറ്റിലെ രക്തസ്രാവം',
            'stomach_pain': 'വയറു വേദന',
            'sunken_eyes': 'മുങ്ങിയ കണ്ണുകൾ',
            'sweating': 'വിയർക്കുന്നു',
            'swelled_lymph_nodes': 'വീർത്ത ലിംഫ് നോഡുകൾ',
            'swelling_joints': 'സന്ധികൾ വീർക്കുന്നു',
            'swelling_of_stomach': 'ആമാശയത്തിലെ വീക്കം',
            'swollen_blood_vessels': 'രക്തക്കുഴലുകൾ വീർക്കുന്നു',
            'swollen_extremeties': 'വീർത്ത തീവ്രത',
            'swollen_legs': 'വീർത്ത കാലുകൾ',
            'throat_irritation': 'തൊണ്ടയിലെ പ്രകോപനം',
            'toxic_look_(typhos)': 'വിഷ രൂപം (ടൈഫോസ്)',
            'ulcers_on_tongue': 'നാവിൽ അൾസർ',
            'unsteadiness': 'അസ്ഥിരത',
            'visual_disturbances': 'ദൃശ്യ അസ്വസ്ഥതകൾ',
            'vomiting': 'ഛർദ്ദി',
            'watering_from_eyes': 'കണ്ണുകളിൽ നിന്ന് നനവ്',
            'weakness_in_limbs': 'കൈകാലുകളിൽ ബലഹീനത',
            'weakness_of_one_body_side': 'ഒരു ശരീരത്തിന്റെ ബലഹീനത',
            'weight_gain': 'ശരീരഭാരം',
            'weight_loss': 'ഭാരനഷ്ടം',
            'yellow_crust_ooze': 'മഞ്ഞ പുറംതോട്',
            'yellow_urine': 'മഞ്ഞ മൂത്രം',
            'yellowing_of_eyes': 'കണ്ണുകളുടെ മഞ്ഞ',
            'yellowish_skin': 'മഞ്ഞകലർന്ന ചർമ്മം',
            'itching': 'ചൊറിച്ചിൽ'}
    elif (lan == 'gujrati'):
        sym = {
            'abdominal_pain': 'પેટ નો દુખાવો',
            'abnormal_menstruation': 'અસામાન્ય માસિક સ્રાવ',
            'acidity': 'એસિડિટી',
            'acute_liver_failure': 'તીવ્ર યકૃત નિષ્ફળતા',
            'altered_sensorium': 'બદલાયેલ સેન્સરિયમ',
            'anxiety': 'ચિંતા',
            'back_pain': 'પીઠનો દુખાવો',
            'belly_pain': 'પેટનો દુખાવો',
            'blackheads': 'બ્લેકહેડ્સ',
            'bladder_discomfort': 'મૂત્રાશયની અગવડતા',
            'blister': 'ફોલ્લો',
            'blood_in_sputum': 'ગળફામાં લોહી',
            'bloody_stool': 'લોહિયાળ સ્ટૂલ',
            'blurred_and_distorted_vision': 'અસ્પષ્ટ અને વિકૃત દ્રષ્ટિ',
            'breathlessness': 'શ્વાસ',
            'brittle_nails': 'બરડ નખ',
            'bruising': 'ઉઝરડો',
            'burning_micturition': 'બળાત્કાર બર્નિંગ',
            'chest_pain': 'છાતીનો દુખાવો',
            'chills': 'ઠંડી',
            'cold_hands_and_feets': 'ઠંડા હાથ અને પગ',
            'coma': 'કોમા',
            'congestion': 'ભીડ',
            'constipation': 'કબજિયાત',
            'continuous_feel_of_urine': 'પેશાબની સતત અનુભૂતિ',
            'continuous_sneezing': 'સતત છીંક આવવી',
            'cough': 'ખાંસી',
            'cramps': 'ખેંચાણ',
            'dark_urine': 'ઘાટો પેશાબ',
            'dehydration': 'ડિહાઇડ્રેશન',
            'depression': 'હતાશા',
            'diarrhoea': 'અતિસાર',
            'dischromic _patches': 'ડિસ્ક્રromમિક પેચો',
            'distention_of_abdomen': 'પેટનો ત્યાગ',
            'dizziness': 'ચક્કર',
            'drying_and_tingling_lips': 'સૂકવણી અને હોઠ કળતર',
            'enlarged_thyroid': 'મોટું થાઇરોઇડ',
            'excessive_hunger': 'અતિશય ભૂખ',
            'extra_marital_contacts': 'વિશેષ વૈવાહિક સંપર્કો',
            'family_history': 'પારિવારિક ઇતિહાસ',
            'fast_heart_rate': 'ઝડપી ધબકારા',
            'fatigue': 'થાક',
            'fluid_overload': 'પ્રવાહી ઓવરલોડ',
            'foul_smell_of urine': 'ગંધની ગંધ',
            'headache': 'માથાનો દુખાવો',
            'high_fever': 'વધારે તાવ',
            'hip_joint_pain': 'હિપ સાંધાનો દુખાવો',
            'history_of_alcohol_consumption': 'આલ્કોહોલ પીવાના ઇતિહાસ',
            'increased_appetite': 'ભૂખ વધી',
            'indigestion': 'અપચો',
            'inflammatory_nails': 'બળતરા નખ',
            'internal_itching': 'આંતરિક ખંજવાળ',
            'irregular_sugar_level': 'ખાંડનું અનિયમિત સ્તર',
            'irritability': 'ચીડિયાપણું',
            'irritation_in_anus': 'ગુદામાં બળતરા',
            'joint_pain': 'સાંધાનો દુખાવો',
            'knee_pain': 'ઘૂંટણની પીડા',
            'lack_of_concentration': 'એકાગ્રતાનો અભાવ',
            'lethargy': 'સુસ્તી',
            'loss_of_appetite': 'ભૂખ ઓછી થવી',
            'loss_of_balance': 'સંતુલન ગુમાવવું',
            'loss_of_smell': 'ગંધ ગુમાવવી',
            'malaise': 'મલાઈઝ',
            'mild_fever': 'હળવો તાવ',
            'mood_swings': 'મૂડ સ્વિંગ',
            'movement_stiffness': 'ચળવળ જડતા',
            'mucoid_sputum': 'મ્યુકોઇડ સ્ફુટમ',
            'muscle_pain': 'સ્નાયુમાં દુખાવો',
            'muscle_wasting': 'સ્નાયુઓનો બગાડ',
            'muscle_weakness': 'સ્નાયુઓની નબળાઇ',
            'nausea': 'ઉબકા',
            'neck_pain': 'ગળામાં દુખાવો',
            'nodal_skin_eruptions': 'નોડલ ત્વચા વિસ્ફોટો',
            'obesity': 'જાડાપણું',
            'pain_behind_the_eyes': 'આંખો પાછળ દુખાવો',
            'pain_during_bowel_movements': 'આંતરડાની હિલચાલ દરમિયાન પીડા',
            'pain_in_anal_region': 'ગુદા પ્રદેશમાં પીડા',
            'painful_walking': 'દુfulખદાયક વ walkingકિંગ',
            'palpitations': 'ધબકારા',
            'passage_of_gases': 'વાયુઓ પસાર',
            'patches_in_throat': 'ગળામાં પેચો',
            'phlegm': 'કફ',
            'polyuria': 'પોલ્યુરિયા',
            'prominent_veins_on_calf': 'વાછરડા પર પ્રખ્યાત નસો',
            'puffy_face_and_eyes': 'ચપળ ચહેરો અને આંખો',
            'pus_filled_pimples': 'પુસ ભરેલા પિમ્પલ્સ',
            'receiving_blood_transfusion': 'લોહી ચfાવવું',
            'receiving_unsterile_injections': 'અનસર્ટિલ ઇન્જેક્શન મેળવવું',
            'red_sore_around_nose': 'નાકની આસપાસ લાલ વ્રણ',
            'red_spots_over_body': 'શરીર ઉપર લાલ ફોલ્લીઓ',
            'redness_of_eyes': 'આંખો લાલાશ',
            'restlessness': 'બેચેની',
            'runny_nose': 'વહેતું નાક',
            'rusty_sputum': 'કાટવાળું ગળફામાં',
            'scurring': 'કર્કશ',
            'shivering': 'ધ્રુજારી',
            'silver_like_dusting': 'ધૂળવા જેવી રજત',
            'sinus_pressure': 'સાઇનસ પ્રેશર',
            'skin_peeling': 'ત્વચા છાલ',
            'skin_rash': 'ત્વચા ફોલ્લીઓ',
            'slurred_speech': 'અસ્પષ્ટ બોલી',
            'small_dents_in_nails': 'નખમાં નાના ડેન્ટ્સ',
            'spinning_movements': 'સ્પિનિંગ હલનચલન',
            'spotting_ urination': 'સ્પોટિંગ પેશાબ',
            'stiff_neck': 'સખત ગરદન',
            'stomach_bleeding': 'પેટમાંથી લોહી નીકળવું',
            'stomach_pain': 'પેટ પીડા',
            'sunken_eyes': 'ડૂબી આંખો',
            'sweating': 'પરસેવો આવે છે',
            'swelled_lymph_nodes': 'સોજો લસિકા ગાંઠો',
            'swelling_joints': 'સોજો સાંધા',
            'swelling_of_stomach': 'પેટમાં સોજો',
            'swollen_blood_vessels': 'રુધિરવાહિનીઓ સોજો',
            'swollen_extremeties': 'સોજો આત્યંતિકતા',
            'swollen_legs': 'સોજો પગ',
            'throat_irritation': 'ગળામાં બળતરા',
            'toxic_look_(typhos)': 'ઝેરી દેખાવ (ટાઇફોસ)',
            'ulcers_on_tongue': 'જીભ પર અલ્સર',
            'unsteadiness': 'અસ્થિરતા',
            'visual_disturbances': 'વિઝ્યુઅલ વિક્ષેપ  ',
            'vomiting': 'ઉલટી',
            'watering_from_eyes': 'આંખોમાંથી પાણી ભરાવું',
            'weakness_in_limbs': 'અંગોમાં નબળાઇ',
            'weakness_of_one_body_side': 'શરીરની એક બાજુની નબળાઇ',
            'weight_gain': 'વજન વધારો',
            'weight_loss': 'વજનમાં ઘટાડો',
            'yellow_crust_ooze': 'પીળો પોપડો',
            'yellow_urine': 'પીળો પેશાબ',
            'yellowing_of_eyes': 'આંખો પીળી',
            'yellowish_skin': 'પીળી ત્વચા',
            'itching': 'ખંજવાળ'}
    return sym


def select_symptoms(request):
    name_v = request.GET.get('Name')
    lan_v = request.GET.get('lang')

    global lan
    global name
    lan = lan_v
    name = name_v

    with open ('name_lan.csv','a') as f:
        writer = csv.writer(f)
        writer.writerow([name,lan,datetime.datetime.now()])

    print(lan)
    header = 'Hello '+name+". Please select your symptoms"
    header = trans(header,lan)

    sym = get_sym(lan)
    sym['header'] = header
    print(header)
    data = {'symptoms':sym}
    return render(request,'sym.html',data)

def pricing(request):
    key_list = get_keys()
    sym_tupple = []
    for i in key_list:
        num = request.GET.get(i)
        if (num != None):
            sym_tupple.append(1)
        else:
            sym_tupple.append(0)

    sym_tupple = np.array(sym_tupple)
    sym_tupple = np.reshape(sym_tupple,(1,-1))

    clf = pickle.load(open('model_clf', 'rb'))

    k = clf.predict(sym_tupple)[0]

    with open('new_data.csv','r') as f:
        reader= csv.reader(f)
        for i in reader:
            try:
                m = int(i[132])
            except:
                m = None
            if(k == m):
                ds = i[131]
                break
        

    return HttpResponse(ds)
